# -*- coding: utf-8 -*-
"""Assessment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGyGHScg9qtD1tZmt4ZcOapeaJGvZIrr

Q 1: Develop a Line chart using the functionality of pandas to show how
automobile sales fluctuate from year to year.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/TopsCode/Data_Analysis_2024/main/ALL_CSV/historical_automobile_sales.csv')
df

# Plot the line chart
plt.figure(figsize=(10, 5))
plt.plot(yearly_sales.index, yearly_sales.values, marker='o', linestyle='-')
plt.xlabel("Year")
plt.ylabel("Total Automobile Sales")
plt.title("Yearly Automobile Sales Fluctuation")
plt.grid(True)
plt.show()

"""Q 2: Plot different lines for categories of vehicle type and analyze the trend
to answer the question Is there a noticeable difference in sales trends
between different vehicle types during recession periods?
"""

vehicle_sales = df.groupby(['Year', 'Vehicle_Type'])['Automobile_Sales'].sum().unstack()

plt.figure(figsize=(12, 6))
for vehicle_type in vehicle_sales.columns:
    plt.plot(vehicle_sales.index, vehicle_sales[vehicle_type], marker='o', label=vehicle_type)

plt.xlabel("Year")
plt.ylabel("Automobile Sales")
plt.title("Sales Trend by Vehicle Type Over the Years")
plt.legend()
plt.grid()
plt.show()

"""Q 3: Use the functionality of Seaborn Library to create a visualization to compare
the sales trend per vehicle type for a recession period with a non- recession
period.
"""

recession_data = df[df['Recession'] == 1]
non_recession_data = df[df['Recession'] == 0]

plt.figure(figsize=(12, 6))
sns.lineplot(data=recession_data, x='Year', y='Automobile_Sales', hue='Vehicle_Type',
             marker='o', linestyle='dashed')
sns.lineplot(data=non_recession_data, x='Year', y='Automobile_Sales', hue='Vehicle_Type',
             marker='D', linestyle='solid')

plt.xlabel("Year")
plt.ylabel("Automobile Sales")
plt.title("Comparison of Vehicle Sales Trends (Recession vs. Non-Recession)")


handles, _ = plt.gca().get_legend_handles_labels()
recession_line = handles[0]
non_recession_line = handles[len(recession_data['Vehicle_Type'].unique())]

plt.legend([recession_line, non_recession_line], ["Recession", "Non-Recession"])

plt.show()

"""Q 4: Now you want to compare the sales of different vehicle types
during a recession and a non-recession period
"""

comparison = df.groupby(['Vehicle_Type', 'Recession'])['Automobile_Sales'].sum().unstack()

comparison.plot(kind='bar', figsize=(10, 6), colormap='coolwarm')
plt.xlabel("Vehicle Type")
plt.ylabel("Total Sales")
plt.title("Comparison of Sales During Recession and Non-Recession Periods")
plt.legend(["Non-Recession", "Recession"])
plt.grid()
plt.show()

