# -*- coding: utf-8 -*-
"""assessment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0Mifq14usfRHbY1QJuRyvHOc1IKB6Mz

1) Import pandas and read in the banklist.csv file into a dataframe called
banks.
"""

import pandas as pd

banks = pd.read_csv("https://raw.githubusercontent.com/TopsCode/Data_Analysis_2024/main/ALL_CSV/banklist.csv")
banks

"""2) Show the head of the dataframe."""

banks.head()

"""3) What are the column names?"""

banks.columns

"""4) How many States (ST) are represented in this data set?"""

num_states = banks['ST'].nunique()

num_states

"""5) Get a list or array of all the states in the data set."""

states_list = banks['ST'].unique()

states_list

"""6) What are the top 5 states with the most failed banks?"""

top5_states = banks['ST'].value_counts().head(5)

top5_states

"""7) What are the top 5 acquiring institutions?"""

top5_acquirers = banks['Acquiring Institution'].value_counts().head(5)

top5_acquirers

"""8) How many banks has the State Bank of Texas acquired? How many of
them were actually in Texas?
"""

acquired_by_texas = banks[banks['Acquiring Institution'] == 'State Bank of Texas']

total_acquired = acquired_by_texas.shape[0]

acquired_texas = acquired_by_texas[acquired_by_texas['ST'] == 'TX'].shape[0]

total_acquired, acquired_texas

"""9) What is the most common city in California for a bank to fail in?"""

ca_banks = banks[banks['ST'] == 'CA']

common_city = ca_banks['City'].mode()[0]
common_city