# -*- coding: utf-8 -*-
"""Assessment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGyGHScg9qtD1tZmt4ZcOapeaJGvZIrr

Q 1: Develop a Line chart using the functionality of pandas to show how
automobile sales fluctuate from year to year.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/TopsCode/Data_Analysis_2024/main/ALL_CSV/historical_automobile_sales.csv')
df

sales_by_year = df.groupby('Year')['Automobile_Sales'].sum()

plt.figure(figsize=(10, 6))
sales_by_year.plot(kind='line', marker='o')
plt.title('Automobile Sales by Yearly')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.grid()
plt.show()

"""Q 2: Plot different lines for categories of vehicle type and analyze the trend
to answer the question Is there a noticeable difference in sales trends
between different vehicle types during recession periods?
"""

recession_data = df[df['Recession'] == 1]
sales_by_type = recession_data.groupby(['Year', 'Vehicle_Type'])['Automobile_Sales'].sum().unstack()

plt.figure(figsize=(12, 6))
sales_by_type.plot(kind='line', marker='o')
plt.title('Sales Trend by Vehicle Type')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.legend(title='Vehicle Type')
plt.show()

"""Q 3: Use the functionality of Seaborn Library to create a visualization to compare
the sales trend per vehicle type for a recession period with a non- recession
period.
"""

recession_sales = df.groupby(['Year', 'Vehicle_Type', 'Recession'])['Automobile_Sales'].sum().reset_index()
plt.figure(figsize=(15,10))
sns.lineplot(data=recession_sales, x='Year', y='Automobile_Sales', hue='Vehicle_Type', marker='o', linestyle='dashed',style='Recession')
plt.xlabel("Year")
plt.ylabel("Automobile Sales")
plt.title("Comparison of Vehicle Sales Trends (Recession vs. Non-Recession)")
plt.legend()
plt.show()

"""Q 4: Now you want to compare the sales of different vehicle types
during a recession and a non-recession period
"""

sns.barplot(data=df,x='Vehicle_Type',y='Automobile_Sales',hue='Recession')
plt.xlabel("Vehicle Type")
plt.ylabel("Total Sales")
plt.title("Comparison of Sales During Recession and Non-Recession Periods")
plt.xticks(rotation=45)
plt.show()

